version: "3"

services:
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: DjangoApp
    restart: always
    #command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DjangoApp:/code
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
