version: "3"

services:
  flaskapp:
    build: flaskapp
    restart: always
    volumes:
      - ./FlaskApp:/code
    ports:
      - "80:5000"
    depends_on:
      - db
  db:
    build: mariadb
    image: mariadb-flaskapp
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password
      TZ: Asia/Tokyo
